- name: Install k3s using k3sup
  command: k3sup install --local
  environment:
    K3S_VERSION: v1.27.16

- name: Set permissions for /etc/rancher/k3s/k3s.yaml
  file:
  path: /etc/rancher/k3s/k3s.yaml
  mode: '0644'
  state: file