prometheus:
  grafana:
    enabled: true

  prometheus:
    prometheusSpec:
      replicas: 2
      retention: 6h
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 25Gi
      thanos:
        objectStorageConfig:
          existingSecret:
            name: prometheus-object-store-config
            key: s3Config
    thanosService:
      enabled: true


thanos:
  query:
    enabled: true
    replicaCount: 1
    stores:
      - dnssrv+_grpc._tcp.monitoring-prometheus-thanos-discovery.monitoring.svc.cluster.local


      #loki:
#  loki:
#    config: |
#      schema_config:
#        configs:
#          - from: 2021-01-01
#            store: boltdb-shipper
#            object_store: s3
#            schema: v11
#            index:
#              prefix: index_
#              period: 24h
#
#    storage:
#      type: s3
#      s3:
#        bucket: loki
#        endpoint: minio.minio.svc.cluster.local:9000
#        accessKeyId: Jw2CuqP17zVehC2WLi6g
#        secretAccessKey: XpL2d8ANKNxkkukacaERWutNgaC1Gn8l8L9js6it
#        insecure: true
#      bucketNames:
#        chunks: loki-chunks
#        ruler: loki-ruler
#        compactor: loki-compactor
      



opentelemetry-collector:
  replicaCount: 2
  mode: daemonset
  image:
    repository: "otel/opentelemetry-collector"
    tag: "latest"

  ports:
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
    otlp-http:
      enabled: false

  config:
    exporters:
      debug: { }
      otlp:
        endpoint:
        headers:
          authorization: ""

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    service:
      extensions:
        - health_check
      pipelines:
        traces:
          exporters:
            - debug
            - otlp
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
